project_id = "bbluqskdwfxfhttcbkqb"

[auth]
additional_redirect_urls = [
  "https://www.majliseaala.com/**",
  "https://www.majliseaala.com/profile",
  "http://localhost:3000/auth/callback**",
  "http://127.0.0.1:3000/auth/callback**",
]
