// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbluqskdwfxfhttcbkqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJibHVxc2tkd2Z4Zmh0dGNia3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgzMzE3NDYsImV4cCI6MjEwMzkwNzc0Nn0.qeGmuE9B7dD8yQAaYexuDGBU6UBYLCDooZgcJ2UsPoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});